# Generated by Django 5.0.14 on 2026-08-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.GenericIPAddressField(unique=True)),
                ('version', models.PositiveSmallIntegerField(choices=[(4, 'IPv4'), (6, 'IPv6')])),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'IP addresses',
                'db_table': 'ip_addresses',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['-last_seen_at'], name='ip_addresse_last_se_61a22f_idx')],
            },
        ),
    ]
