# Generated by Django 5.0.14 on 2026-08-26 03:52

import apps.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='asn',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='cidr',
            field=apps.common.fields.CIDRField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='continent',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='country_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='iran_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='iran_match_cidr',
            field=apps.common.fields.CIDRField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='is_iran',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='network',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='organization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='whois_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='whois_country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='whois_next_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='whois_status',
            field=models.CharField(choices=[('never_checked', 'Never checked'), ('ok', 'OK'), ('error', 'Error')], default='never_checked', max_length=15),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['is_iran'], name='ip_addresse_is_iran_7bafcd_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['country_code'], name='ip_addresse_country_963110_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['asn'], name='ip_addresse_asn_e1cbf4_idx'),
        ),
    ]
