# Generated by Django 5.0.14 on 2026-08-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0002_add_intelligence_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='whois_error',
            field=models.TextField(blank=True),
        ),
    ]
