# Generated by Django 5.0.14 on 2026-08-26 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ips', '0003_ipaddress_whois_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queried_at', models.DateTimeField()),
                ('whois_server', models.CharField(blank=True, max_length=255)),
                ('raw_response', models.TextField()),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('response_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whois_records', to='ips.ipaddress')),
            ],
            options={
                'db_table': 'whois_records',
                'ordering': ['-queried_at'],
                'indexes': [models.Index(fields=['ip', '-queried_at'], name='whois_recor_ip_id_db2acf_idx'), models.Index(fields=['-queried_at'], name='whois_recor_queried_429f58_idx')],
            },
        ),
    ]
