# Generated by Django 5.2.17 on 2026-09-03 18:40

import apps.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whois', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservedNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cidr', apps.common.fields.CIDRField(unique=True)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('network', models.CharField(blank=True, max_length=255)),
                ('asn', models.PositiveBigIntegerField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('hit_count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'observed_networks',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['country_code'], name='observed_ne_country_c01962_idx'), models.Index(fields=['-last_seen_at'], name='observed_ne_last_se_07eb89_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProxyEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('scheme', models.CharField(choices=[('socks5', 'SOCKS5'), ('socks5h', 'SOCKS5 (remote DNS)'), ('socks4', 'SOCKS4')], default='socks5', max_length=10)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField()),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', apps.common.fields.EncryptedTextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('total_uses', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'whois_proxy_endpoints',
                'ordering': ['host', 'port'],
                'constraints': [models.UniqueConstraint(fields=('host', 'port'), name='unique_proxy_host_port')],
            },
        ),
    ]
