# Generated by Django 5.0.14 on 2026-08-26 05:47

import apps.common.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ips', '0003_ipaddress_whois_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPCountryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('source', models.CharField(max_length=50)),
                ('cidr', apps.common.fields.CIDRField(blank=True, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'IP country history',
                'db_table': 'ip_country_history',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='CountryNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_code', models.CharField(max_length=2)),
                ('cidr', apps.common.fields.CIDRField()),
                ('network', models.CharField(blank=True, max_length=255)),
                ('prefix_length', models.PositiveSmallIntegerField(editable=False)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Country networks',
                'db_table': 'country_networks',
                'ordering': ['country_code', 'cidr'],
                'indexes': [models.Index(fields=['country_code'], name='country_net_country_ea1815_idx'), models.Index(fields=['enabled'], name='country_net_enabled_1eb143_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='countrynetwork',
            constraint=models.UniqueConstraint(fields=('country_code', 'cidr'), name='unique_country_cidr'),
        ),
        migrations.AddField(
            model_name='ipcountryhistory',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_history', to='ips.ipaddress'),
        ),
        migrations.AddIndex(
            model_name='ipcountryhistory',
            index=models.Index(fields=['ip', '-valid_from'], name='ip_country__ip_id_5d8ab2_idx'),
        ),
        migrations.AddIndex(
            model_name='ipcountryhistory',
            index=models.Index(fields=['country_code'], name='ip_country__country_b5e68a_idx'),
        ),
    ]
