# Generated by Django 5.0.14 on 2026-08-26 01:54

import apps.common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hostname', models.CharField(help_text='DNS name or IP address used to connect.', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('ssh_port', models.PositiveIntegerField(default=22)),
                ('ssh_username', models.CharField(max_length=100)),
                ('ssh_auth_type', models.CharField(choices=[('ssh_key', 'SSH Key'), ('password', 'Password')], default='ssh_key', max_length=10)),
                ('ssh_private_key', apps.common.fields.EncryptedTextField(blank=True)),
                ('log_search_paths', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'servers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['enabled'], name='servers_enabled_af117b_idx')],
            },
        ),
    ]
