# Generated by Django 5.0.14 on 2026-08-26 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Usually the file's basename.", max_length=255)),
                ('path', models.CharField(max_length=1024)),
                ('format', models.CharField(default='combined', help_text='Nginx log_format name this file is written in. Used by the parser from Phase 3 onward.', max_length=50)),
                ('enabled', models.BooleanField(default=False, help_text='Whether the reader should monitor this file.')),
                ('inode', models.BigIntegerField(blank=True, null=True)),
                ('byte_offset', models.BigIntegerField(default=0)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sources', to='servers.server')),
            ],
            options={
                'db_table': 'log_sources',
                'ordering': ['server__name', 'path'],
                'indexes': [models.Index(fields=['server', 'enabled'], name='log_sources_server__70a74d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='logsource',
            constraint=models.UniqueConstraint(fields=('server', 'path'), name='unique_log_source_per_server_path'),
        ),
    ]
