# Generated by Django 5.0.14 on 2026-08-26 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ips', '0001_initial'),
        ('logs', '0001_initial'),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('host', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(blank=True, max_length=16)),
                ('uri', models.CharField(blank=True, max_length=2048)),
                ('status', models.PositiveSmallIntegerField()),
                ('bytes', models.PositiveBigIntegerField(default=0)),
                ('request_time', models.FloatField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('referer', models.CharField(blank=True, max_length=2048)),
                ('raw_line', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_events', to='ips.ipaddress')),
                ('log_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_events', to='logs.logsource')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_events', to='servers.server')),
            ],
            options={
                'db_table': 'request_events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='request_eve_timesta_ad99ab_idx'), models.Index(fields=['ip', '-timestamp'], name='request_eve_ip_id_5868f3_idx'), models.Index(fields=['server', '-timestamp'], name='request_eve_server__c63267_idx'), models.Index(fields=['status'], name='request_eve_status_87e8fd_idx')],
            },
        ),
    ]
